# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\spectrum.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SpectrumAssignment(object):
    def setupUi(self, SpectrumAssignment):
        SpectrumAssignment.setObjectName("SpectrumAssignment")
        SpectrumAssignment.resize(768, 499)
        self.centralwidget = QtWidgets.QWidget(SpectrumAssignment)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.toolbar = QtWidgets.QWidget(self.centralwidget)
        self.toolbar.setObjectName("toolbar")
        self.gridLayout.addWidget(self.toolbar, 0, 0, 1, 1)
        self.canvas = QtWidgets.QWidget(self.centralwidget)
        self.canvas.setObjectName("canvas")
        self.gridLayout.addWidget(self.canvas, 1, 0, 1, 1)
        self.navigation = QtWidgets.QGroupBox(self.centralwidget)
        self.navigation.setObjectName("navigation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.navigation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.navigation)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.navigation)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 4, 1, 1)
        self.assign_goto_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_goto_btn.setObjectName("assign_goto_btn")
        self.gridLayout_2.addWidget(self.assign_goto_btn, 1, 0, 1, 1)
        self.assign_goto_edit = QtWidgets.QLineEdit(self.navigation)
        self.assign_goto_edit.setObjectName("assign_goto_edit")
        self.gridLayout_2.addWidget(self.assign_goto_edit, 1, 1, 1, 1)
        self.assign_score_good_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_score_good_btn.setStyleSheet("QPushButton:pressed {background-color: rgb(154,205,50)}\n"
"QPushButton {background-color: rgb(124,252,0)}")
        self.assign_score_good_btn.setObjectName("assign_score_good_btn")
        self.gridLayout_2.addWidget(self.assign_score_good_btn, 1, 3, 1, 1)
        self.assign_filter_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_filter_btn.setObjectName("assign_filter_btn")
        self.gridLayout_2.addWidget(self.assign_filter_btn, 2, 0, 1, 1)
        self.assign_filter_dropdown = QtWidgets.QComboBox(self.navigation)
        self.assign_filter_dropdown.setObjectName("assign_filter_dropdown")
        self.assign_filter_dropdown.addItem("")
        self.assign_filter_dropdown.addItem("")
        self.gridLayout_2.addWidget(self.assign_filter_dropdown, 2, 1, 1, 1)
        self.assign_filter_edit = QtWidgets.QLineEdit(self.navigation)
        self.assign_filter_edit.setObjectName("assign_filter_edit")
        self.gridLayout_2.addWidget(self.assign_filter_edit, 2, 2, 1, 1)
        self.assign_score_accept = QtWidgets.QPushButton(self.navigation)
        self.assign_score_accept.setStyleSheet("QPushButton:pressed {background-color: rgb(154,205,50)}\n"
"QPushButton {background-color: rgb(107,142,35)}")
        self.assign_score_accept.setObjectName("assign_score_accept")
        self.gridLayout_2.addWidget(self.assign_score_accept, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.navigation)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.navigation)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 5, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.navigation)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 2, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.navigation)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 7, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.navigation)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 2, 8, 1, 1)
        self.assign_score_unsure_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_score_unsure_btn.setStyleSheet("QPushButton:pressed {background-color: rgb(255,215,0)}\n"
"QPushButton {background-color: rgb(255,165,0)}")
        self.assign_score_unsure_btn.setObjectName("assign_score_unsure_btn")
        self.gridLayout_2.addWidget(self.assign_score_unsure_btn, 3, 3, 1, 1)
        self.assign_previous_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_previous_btn.setObjectName("assign_previous_btn")
        self.gridLayout_2.addWidget(self.assign_previous_btn, 4, 0, 1, 1)
        self.assign_score_decline_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_score_decline_btn.setStyleSheet("QPushButton {background-color: rgb(220,20,60)}\n"
"QPushButton:pressed {background-color: rgb(250,128,114)}")
        self.assign_score_decline_btn.setObjectName("assign_score_decline_btn")
        self.gridLayout_2.addWidget(self.assign_score_decline_btn, 4, 3, 1, 1)
        self.assign_next_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_next_btn.setObjectName("assign_next_btn")
        self.gridLayout_2.addWidget(self.assign_next_btn, 4, 8, 1, 1)
        self.gridLayout.addWidget(self.navigation, 2, 0, 1, 1)
        SpectrumAssignment.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SpectrumAssignment)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        SpectrumAssignment.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SpectrumAssignment)
        self.statusbar.setObjectName("statusbar")
        SpectrumAssignment.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(SpectrumAssignment)
        self.actionQuit.setObjectName("actionQuit")
        self.assign_options = QtWidgets.QAction(SpectrumAssignment)
        self.assign_options.setObjectName("assign_options")
        self.menuFile.addAction(self.assign_options)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(SpectrumAssignment)
        self.assign_filter_dropdown.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SpectrumAssignment)

    def retranslateUi(self, SpectrumAssignment):
        _translate = QtCore.QCoreApplication.translate
        SpectrumAssignment.setWindowTitle(_translate("SpectrumAssignment", "Spectrum Assignment"))
        self.navigation.setTitle(_translate("SpectrumAssignment", "Navigation"))
        self.label_5.setText(_translate("SpectrumAssignment", "Current xlink:"))
        self.label_4.setText(_translate("SpectrumAssignment", "Current Spectrum"))
        self.assign_goto_btn.setText(_translate("SpectrumAssignment", "GoTo"))
        self.assign_score_good_btn.setText(_translate("SpectrumAssignment", "Very Good [3]"))
        self.assign_score_good_btn.setShortcut(_translate("SpectrumAssignment", "3"))
        self.assign_filter_btn.setText(_translate("SpectrumAssignment", "Filter score"))
        self.assign_filter_dropdown.setCurrentText(_translate("SpectrumAssignment", "Less than"))
        self.assign_filter_dropdown.setItemText(0, _translate("SpectrumAssignment", "Less than"))
        self.assign_filter_dropdown.setItemText(1, _translate("SpectrumAssignment", "Greater than"))
        self.assign_score_accept.setText(_translate("SpectrumAssignment", "Accept [2]"))
        self.assign_score_accept.setShortcut(_translate("SpectrumAssignment", "2"))
        self.label_6.setText(_translate("SpectrumAssignment", "Precision (ppm)"))
        self.label_7.setText(_translate("SpectrumAssignment", "-"))
        self.label_8.setText(_translate("SpectrumAssignment", "+"))
        self.assign_score_unsure_btn.setText(_translate("SpectrumAssignment", "Unsure [1]"))
        self.assign_score_unsure_btn.setShortcut(_translate("SpectrumAssignment", "1"))
        self.assign_previous_btn.setText(_translate("SpectrumAssignment", "Previous"))
        self.assign_score_decline_btn.setText(_translate("SpectrumAssignment", "Decline [0]"))
        self.assign_score_decline_btn.setShortcut(_translate("SpectrumAssignment", "0"))
        self.assign_next_btn.setText(_translate("SpectrumAssignment", "Next"))
        self.menuFile.setTitle(_translate("SpectrumAssignment", "File"))
        self.actionQuit.setText(_translate("SpectrumAssignment", "Quit"))
        self.assign_options.setText(_translate("SpectrumAssignment", "Options"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpectrumAssignment = QtWidgets.QMainWindow()
    ui = Ui_SpectrumAssignment()
    ui.setupUi(SpectrumAssignment)
    SpectrumAssignment.show()
    sys.exit(app.exec_())

