# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CroCo_qt.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(635, 319)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_lbl = QtWidgets.QLabel(self.tab)
        self.input_lbl.setObjectName("input_lbl")
        self.gridLayout_2.addWidget(self.input_lbl, 0, 0, 1, 2)
        self.input_dropdown = QtWidgets.QComboBox(self.tab)
        self.input_dropdown.setObjectName("input_dropdown")
        self.gridLayout_2.addWidget(self.input_dropdown, 0, 2, 1, 1)
        self.output_lbl = QtWidgets.QLabel(self.tab)
        self.output_lbl.setObjectName("output_lbl")
        self.gridLayout_2.addWidget(self.output_lbl, 0, 3, 1, 1)
        self.output_dropdown = QtWidgets.QComboBox(self.tab)
        self.output_dropdown.setObjectName("output_dropdown")
        self.gridLayout_2.addWidget(self.output_dropdown, 0, 4, 1, 2)
        self.fbtn = QtWidgets.QPushButton(self.tab)
        self.fbtn.setObjectName("fbtn")
        self.gridLayout_2.addWidget(self.fbtn, 1, 2, 1, 1)
        self.obtn = QtWidgets.QPushButton(self.tab)
        self.obtn.setObjectName("obtn")
        self.gridLayout_2.addWidget(self.obtn, 1, 4, 1, 2)
        self.inpath_title = QtWidgets.QLabel(self.tab)
        self.inpath_title.setObjectName("inpath_title")
        self.gridLayout_2.addWidget(self.inpath_title, 2, 0, 1, 1)
        self.inpath_lbl = QtWidgets.QLabel(self.tab)
        self.inpath_lbl.setText("")
        self.inpath_lbl.setObjectName("inpath_lbl")
        self.gridLayout_2.addWidget(self.inpath_lbl, 2, 1, 1, 2)
        self.outpath_title = QtWidgets.QLabel(self.tab)
        self.outpath_title.setObjectName("outpath_title")
        self.gridLayout_2.addWidget(self.outpath_title, 2, 3, 1, 2)
        self.outpath_lbl = QtWidgets.QLabel(self.tab)
        self.outpath_lbl.setText("")
        self.outpath_lbl.setObjectName("outpath_lbl")
        self.gridLayout_2.addWidget(self.outpath_lbl, 2, 5, 1, 1)
        self.sbtn = QtWidgets.QPushButton(self.tab)
        self.sbtn.setObjectName("sbtn")
        self.gridLayout_2.addWidget(self.sbtn, 3, 1, 1, 2)
        self.qbtn = QtWidgets.QPushButton(self.tab)
        self.qbtn.setObjectName("qbtn")
        self.gridLayout_2.addWidget(self.qbtn, 3, 4, 1, 2)
        self.outpath_lbl.raise_()
        self.inpath_title.raise_()
        self.qbtn.raise_()
        self.output_lbl.raise_()
        self.fbtn.raise_()
        self.sbtn.raise_()
        self.obtn.raise_()
        self.input_lbl.raise_()
        self.outpath_title.raise_()
        self.inpath_lbl.raise_()
        self.input_dropdown.raise_()
        self.output_dropdown.raise_()
        self.outpath_lbl.raise_()
        self.inpath_title.raise_()
        self.qbtn.raise_()
        self.output_lbl.raise_()
        self.fbtn.raise_()
        self.sbtn.raise_()
        self.obtn.raise_()
        self.input_lbl.raise_()
        self.outpath_title.raise_()
        self.inpath_lbl.raise_()
        self.input_dropdown.raise_()
        self.output_dropdown.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setStyleSheet("QPushButton:pressed {background-color: rgb(255,215,0)}\n"
"QPushButton {background-color: rgb(255,165,0)}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 8, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 8, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 2)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 8, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 3, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 9, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 6, 5, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 6, 6, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 9, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setStyleSheet("QPushButton:pressed {background-color: rgb(154,205,50)}\n"
"QPushButton {background-color: rgb(107,142,35)}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 6, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setStyleSheet("QPushButton {background-color: rgb(220,20,60)}\n"
"QPushButton:pressed {background-color: rgb(250,128,114)}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 9, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 7)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setStyleSheet("QPushButton:pressed {background-color: rgb(154,205,50)}\n"
"QPushButton {background-color: rgb(124,252,0)}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 5, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 635, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout_CroCo = QtWidgets.QAction(MainWindow)
        self.actionAbout_CroCo.setObjectName("actionAbout_CroCo")
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout_CroCo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "The CroCo Cross-Link Converter"))
        self.input_lbl.setText(_translate("MainWindow", "Input file format:"))
        self.output_lbl.setText(_translate("MainWindow", "Output File Format"))
        self.fbtn.setText(_translate("MainWindow", "Load file(s)"))
        self.obtn.setText(_translate("MainWindow", "Output Dir"))
        self.inpath_title.setText(_translate("MainWindow", "Reading From:"))
        self.outpath_title.setText(_translate("MainWindow", "Writing To:"))
        self.sbtn.setText(_translate("MainWindow", "Start"))
        self.qbtn.setText(_translate("MainWindow", "Quit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Conversion"))
        self.label_5.setText(_translate("MainWindow", "Current xlink:"))
        self.pushButton_6.setText(_translate("MainWindow", "Unsure"))
        self.label_2.setText(_translate("MainWindow", "Load MGF:"))
        self.pushButton_9.setText(_translate("MainWindow", "GoTo"))
        self.pushButton_3.setText(_translate("MainWindow", "Start assignment"))
        self.pushButton_2.setText(_translate("MainWindow", "Load MGF"))
        self.pushButton_11.setText(_translate("MainWindow", "Next"))
        self.label_4.setText(_translate("MainWindow", "Current Spectrum"))
        self.label_6.setText(_translate("MainWindow", "Precision"))
        self.label_3.setText(_translate("MainWindow", "Output Dir:"))
        self.pushButton.setText(_translate("MainWindow", "Load xlink"))
        self.pushButton_7.setText(_translate("MainWindow", "Output Dir"))
        self.label.setText(_translate("MainWindow", "Load xlinks:"))
        self.pushButton_10.setText(_translate("MainWindow", "Previous"))
        self.pushButton_4.setText(_translate("MainWindow", "Accept"))
        self.pushButton_8.setText(_translate("MainWindow", "Decline"))
        self.pushButton_5.setText(_translate("MainWindow", "Very Good"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Assignment"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout_CroCo.setText(_translate("MainWindow", "About CroCo"))

