# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/CroCo_qt.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(456, 233)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/data/images/python-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label3 = QtWidgets.QLabel(self.widget)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 0, 0, 1, 1)
        self.convert_input_dropdown = QtWidgets.QComboBox(self.widget)
        self.convert_input_dropdown.setObjectName("convert_input_dropdown")
        self.convert_input_dropdown.addItem("")
        self.convert_input_dropdown.addItem("")
        self.convert_input_dropdown.addItem("")
        self.convert_input_dropdown.addItem("")
        self.convert_input_dropdown.addItem("")
        self.gridLayout.addWidget(self.convert_input_dropdown, 0, 1, 1, 1)
        self.label4 = QtWidgets.QLabel(self.widget)
        self.label4.setObjectName("label4")
        self.gridLayout.addWidget(self.label4, 0, 2, 1, 1)
        self.convert_output_dropdown = QtWidgets.QComboBox(self.widget)
        self.convert_output_dropdown.setObjectName("convert_output_dropdown")
        self.convert_output_dropdown.addItem("")
        self.convert_output_dropdown.addItem("")
        self.convert_output_dropdown.addItem("")
        self.convert_output_dropdown.addItem("")
        self.convert_output_dropdown.addItem("")
        self.gridLayout.addWidget(self.convert_output_dropdown, 0, 3, 1, 1)
        self.convert_load_btn = QtWidgets.QPushButton(self.widget)
        self.convert_load_btn.setObjectName("convert_load_btn")
        self.gridLayout.addWidget(self.convert_load_btn, 1, 1, 1, 1)
        self.convert_output_btn = QtWidgets.QPushButton(self.widget)
        self.convert_output_btn.setObjectName("convert_output_btn")
        self.gridLayout.addWidget(self.convert_output_btn, 1, 3, 1, 1)
        self.label1 = QtWidgets.QLabel(self.widget)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 2, 0, 1, 1)
        self.label2 = QtWidgets.QLabel(self.widget)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 2, 2, 1, 2)
        self.convert_start = QtWidgets.QPushButton(self.widget)
        self.convert_start.setObjectName("convert_start")
        self.gridLayout.addWidget(self.convert_start, 4, 0, 1, 1)
        self.convert_quit = QtWidgets.QPushButton(self.widget)
        self.convert_quit.setObjectName("convert_quit")
        self.gridLayout.addWidget(self.convert_quit, 4, 3, 1, 1)
        self.convert_input_lbl = QtWidgets.QLabel(self.widget)
        self.convert_input_lbl.setText("")
        self.convert_input_lbl.setObjectName("convert_input_lbl")
        self.gridLayout.addWidget(self.convert_input_lbl, 3, 0, 1, 1)
        self.convert_output_lbl = QtWidgets.QLabel(self.widget)
        self.convert_output_lbl.setText("")
        self.convert_output_lbl.setObjectName("convert_output_lbl")
        self.gridLayout.addWidget(self.convert_output_lbl, 3, 2, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 456, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtWidgets.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "The CroCo Cross-Link Converter"))
        self.label3.setText(_translate("MainWindow", "Input file format:"))
        self.convert_input_dropdown.setStatusTip(_translate("MainWindow", "Format for file input"))
        self.convert_input_dropdown.setItemText(0, _translate("MainWindow", "pLink1"))
        self.convert_input_dropdown.setItemText(1, _translate("MainWindow", "pLink2"))
        self.convert_input_dropdown.setItemText(2, _translate("MainWindow", "xQuest"))
        self.convert_input_dropdown.setItemText(3, _translate("MainWindow", "Kojak"))
        self.convert_input_dropdown.setItemText(4, _translate("MainWindow", "xTable"))
        self.label4.setText(_translate("MainWindow", "Output File Format"))
        self.convert_output_dropdown.setStatusTip(_translate("MainWindow", "Format to convert file to"))
        self.convert_output_dropdown.setItemText(0, _translate("MainWindow", "xTable"))
        self.convert_output_dropdown.setItemText(1, _translate("MainWindow", "xVis"))
        self.convert_output_dropdown.setItemText(2, _translate("MainWindow", "xiNet"))
        self.convert_output_dropdown.setItemText(3, _translate("MainWindow", "DynamXL"))
        self.convert_output_dropdown.setItemText(4, _translate("MainWindow", "xWalk"))
        self.convert_load_btn.setStatusTip(_translate("MainWindow", "Load input files"))
        self.convert_load_btn.setText(_translate("MainWindow", "Load file(s)"))
        self.convert_output_btn.setStatusTip(_translate("MainWindow", "Select the output directory"))
        self.convert_output_btn.setText(_translate("MainWindow", "Output Dir"))
        self.label1.setText(_translate("MainWindow", "Reading From:"))
        self.label2.setText(_translate("MainWindow", "Writing To:"))
        self.convert_start.setStatusTip(_translate("MainWindow", "Start the conversion"))
        self.convert_start.setText(_translate("MainWindow", "Start"))
        self.convert_quit.setStatusTip(_translate("MainWindow", "Quit the programme"))
        self.convert_quit.setText(_translate("MainWindow", "Quit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Exit the programme"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About CroCo"))
        self.actionAbout.setStatusTip(_translate("MainWindow", "About CroCo"))

from . import croco_rc
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

