# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\spectrum.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Spectrum(object):
    def setupUi(self, Spectrum):
        Spectrum.setObjectName("Spectrum")
        Spectrum.resize(715, 397)
        Spectrum.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/data/images/python-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Spectrum.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Spectrum)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbar = QtWidgets.QWidget(Spectrum)
        self.toolbar.setObjectName("toolbar")
        self.verticalLayout.addWidget(self.toolbar)
        self.canvas = QtWidgets.QWidget(Spectrum)
        self.canvas.setBaseSize(QtCore.QSize(0, 0))
        self.canvas.setObjectName("canvas")
        self.verticalLayout.addWidget(self.canvas)
        self.navigation = QtWidgets.QGroupBox(Spectrum)
        self.navigation.setObjectName("navigation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.navigation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.navigation)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.navigation)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 4, 1, 1)
        self.assign_goto_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_goto_btn.setObjectName("assign_goto_btn")
        self.gridLayout_2.addWidget(self.assign_goto_btn, 1, 0, 1, 1)
        self.assign_goto_edit = QtWidgets.QLineEdit(self.navigation)
        self.assign_goto_edit.setObjectName("assign_goto_edit")
        self.gridLayout_2.addWidget(self.assign_goto_edit, 1, 1, 1, 1)
        self.assign_score_good_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_score_good_btn.setStyleSheet("QPushButton:pressed {background-color: rgb(154,205,50)}\n"
"QPushButton {background-color: rgb(124,252,0)}")
        self.assign_score_good_btn.setObjectName("assign_score_good_btn")
        self.gridLayout_2.addWidget(self.assign_score_good_btn, 1, 3, 1, 1)
        self.assign_filter_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_filter_btn.setObjectName("assign_filter_btn")
        self.gridLayout_2.addWidget(self.assign_filter_btn, 2, 0, 1, 1)
        self.assign_filter_dropdown = QtWidgets.QComboBox(self.navigation)
        self.assign_filter_dropdown.setObjectName("assign_filter_dropdown")
        self.assign_filter_dropdown.addItem("")
        self.assign_filter_dropdown.addItem("")
        self.gridLayout_2.addWidget(self.assign_filter_dropdown, 2, 1, 1, 1)
        self.assign_filter_edit = QtWidgets.QLineEdit(self.navigation)
        self.assign_filter_edit.setObjectName("assign_filter_edit")
        self.gridLayout_2.addWidget(self.assign_filter_edit, 2, 2, 1, 1)
        self.assign_score_accept = QtWidgets.QPushButton(self.navigation)
        self.assign_score_accept.setStyleSheet("QPushButton:pressed {background-color: rgb(154,205,50)}\n"
"QPushButton {background-color: rgb(107,142,35)}")
        self.assign_score_accept.setObjectName("assign_score_accept")
        self.gridLayout_2.addWidget(self.assign_score_accept, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.navigation)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.navigation)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 5, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.navigation)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 2, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.navigation)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 7, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.navigation)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 2, 8, 1, 1)
        self.assign_score_unsure_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_score_unsure_btn.setStyleSheet("QPushButton:pressed {background-color: rgb(255,215,0)}\n"
"QPushButton {background-color: rgb(255,165,0)}")
        self.assign_score_unsure_btn.setObjectName("assign_score_unsure_btn")
        self.gridLayout_2.addWidget(self.assign_score_unsure_btn, 3, 3, 1, 1)
        self.assign_previous_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_previous_btn.setObjectName("assign_previous_btn")
        self.gridLayout_2.addWidget(self.assign_previous_btn, 4, 0, 1, 1)
        self.assign_score_decline_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_score_decline_btn.setStyleSheet("QPushButton {background-color: rgb(220,20,60)}\n"
"QPushButton:pressed {background-color: rgb(250,128,114)}")
        self.assign_score_decline_btn.setObjectName("assign_score_decline_btn")
        self.gridLayout_2.addWidget(self.assign_score_decline_btn, 4, 3, 1, 1)
        self.assign_next_btn = QtWidgets.QPushButton(self.navigation)
        self.assign_next_btn.setObjectName("assign_next_btn")
        self.gridLayout_2.addWidget(self.assign_next_btn, 4, 8, 1, 1)
        self.verticalLayout.addWidget(self.navigation)

        self.retranslateUi(Spectrum)
        self.assign_filter_dropdown.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Spectrum)

    def retranslateUi(self, Spectrum):
        _translate = QtCore.QCoreApplication.translate
        Spectrum.setWindowTitle(_translate("Spectrum", "Spectrum Assignment"))
        self.navigation.setTitle(_translate("Spectrum", "Navigation"))
        self.label_5.setText(_translate("Spectrum", "Current xlink:"))
        self.label_4.setText(_translate("Spectrum", "Current Spectrum"))
        self.assign_goto_btn.setText(_translate("Spectrum", "GoTo"))
        self.assign_score_good_btn.setText(_translate("Spectrum", "Very Good [3]"))
        self.assign_score_good_btn.setShortcut(_translate("Spectrum", "G"))
        self.assign_filter_btn.setText(_translate("Spectrum", "Filter score"))
        self.assign_filter_dropdown.setCurrentText(_translate("Spectrum", "Less than"))
        self.assign_filter_dropdown.setItemText(0, _translate("Spectrum", "Less than"))
        self.assign_filter_dropdown.setItemText(1, _translate("Spectrum", "Greater than"))
        self.assign_score_accept.setText(_translate("Spectrum", "Accept [2]"))
        self.assign_score_accept.setShortcut(_translate("Spectrum", "2"))
        self.label_6.setText(_translate("Spectrum", "Precision (ppm)"))
        self.label_7.setText(_translate("Spectrum", "-"))
        self.label_8.setText(_translate("Spectrum", "+"))
        self.assign_score_unsure_btn.setText(_translate("Spectrum", "Unsure [1]"))
        self.assign_score_unsure_btn.setShortcut(_translate("Spectrum", "1"))
        self.assign_previous_btn.setText(_translate("Spectrum", "Previous"))
        self.assign_score_decline_btn.setText(_translate("Spectrum", "Decline [0]"))
        self.assign_score_decline_btn.setShortcut(_translate("Spectrum", "0"))
        self.assign_next_btn.setText(_translate("Spectrum", "Next"))

import croco_qt.croco_rc
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Spectrum = QtWidgets.QWidget()
    ui = Ui_Spectrum()
    ui.setupUi(Spectrum)
    Spectrum.show()
    sys.exit(app.exec_())

