# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\CroCo_qt.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(788, 347)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/data/images/python-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.progressBar)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label3 = QtWidgets.QLabel(self.tab)
        self.label3.setObjectName("label3")
        self.gridLayout_2.addWidget(self.label3, 0, 0, 1, 2)
        self.convert_input_dropdown = QtWidgets.QComboBox(self.tab)
        self.convert_input_dropdown.setObjectName("convert_input_dropdown")
        self.convert_input_dropdown.addItem("")
        self.convert_input_dropdown.addItem("")
        self.convert_input_dropdown.addItem("")
        self.gridLayout_2.addWidget(self.convert_input_dropdown, 0, 2, 1, 1)
        self.label4 = QtWidgets.QLabel(self.tab)
        self.label4.setObjectName("label4")
        self.gridLayout_2.addWidget(self.label4, 0, 3, 1, 1)
        self.convert_output_dropdown = QtWidgets.QComboBox(self.tab)
        self.convert_output_dropdown.setObjectName("convert_output_dropdown")
        self.convert_output_dropdown.addItem("")
        self.gridLayout_2.addWidget(self.convert_output_dropdown, 0, 4, 1, 2)
        self.convert_load_btn = QtWidgets.QPushButton(self.tab)
        self.convert_load_btn.setObjectName("convert_load_btn")
        self.gridLayout_2.addWidget(self.convert_load_btn, 1, 2, 1, 1)
        self.convert_output_btn = QtWidgets.QPushButton(self.tab)
        self.convert_output_btn.setObjectName("convert_output_btn")
        self.gridLayout_2.addWidget(self.convert_output_btn, 1, 4, 1, 2)
        self.label1 = QtWidgets.QLabel(self.tab)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 2, 0, 1, 1)
        self.convert_input_lbl = QtWidgets.QLabel(self.tab)
        self.convert_input_lbl.setText("")
        self.convert_input_lbl.setObjectName("convert_input_lbl")
        self.gridLayout_2.addWidget(self.convert_input_lbl, 2, 1, 1, 2)
        self.label2 = QtWidgets.QLabel(self.tab)
        self.label2.setObjectName("label2")
        self.gridLayout_2.addWidget(self.label2, 2, 3, 1, 2)
        self.convert_output_lbl = QtWidgets.QLabel(self.tab)
        self.convert_output_lbl.setText("")
        self.convert_output_lbl.setObjectName("convert_output_lbl")
        self.gridLayout_2.addWidget(self.convert_output_lbl, 2, 5, 1, 1)
        self.convert_quit = QtWidgets.QPushButton(self.tab)
        self.convert_quit.setObjectName("convert_quit")
        self.gridLayout_2.addWidget(self.convert_quit, 3, 4, 1, 2)
        self.convert_start = QtWidgets.QPushButton(self.tab)
        self.convert_start.setObjectName("convert_start")
        self.gridLayout_2.addWidget(self.convert_start, 3, 0, 1, 1)
        self.convert_output_lbl.raise_()
        self.label1.raise_()
        self.convert_quit.raise_()
        self.label4.raise_()
        self.convert_load_btn.raise_()
        self.convert_output_btn.raise_()
        self.label3.raise_()
        self.label2.raise_()
        self.convert_input_lbl.raise_()
        self.convert_input_dropdown.raise_()
        self.convert_output_dropdown.raise_()
        self.convert_start.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.assign_next_btn = QtWidgets.QPushButton(self.tab_2)
        self.assign_next_btn.setObjectName("assign_next_btn")
        self.gridLayout.addWidget(self.assign_next_btn, 9, 8, 1, 1)
        self.assign_score_decline_btn = QtWidgets.QPushButton(self.tab_2)
        self.assign_score_decline_btn.setStyleSheet("QPushButton {background-color: rgb(220,20,60)}\n"
"QPushButton:pressed {background-color: rgb(250,128,114)}")
        self.assign_score_decline_btn.setObjectName("assign_score_decline_btn")
        self.gridLayout.addWidget(self.assign_score_decline_btn, 9, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.assign_score_unsure_btn = QtWidgets.QPushButton(self.tab_2)
        self.assign_score_unsure_btn.setStyleSheet("QPushButton:pressed {background-color: rgb(255,215,0)}\n"
"QPushButton {background-color: rgb(255,165,0)}")
        self.assign_score_unsure_btn.setObjectName("assign_score_unsure_btn")
        self.gridLayout.addWidget(self.assign_score_unsure_btn, 8, 3, 1, 1)
        self.assign_start_btn = QtWidgets.QPushButton(self.tab_2)
        self.assign_start_btn.setObjectName("assign_start_btn")
        self.gridLayout.addWidget(self.assign_start_btn, 2, 3, 1, 1)
        self.assign_load_mgf_btn = QtWidgets.QPushButton(self.tab_2)
        self.assign_load_mgf_btn.setObjectName("assign_load_mgf_btn")
        self.gridLayout.addWidget(self.assign_load_mgf_btn, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 4, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 6, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 4, 1, 1)
        self.assign_load_xlink_btn = QtWidgets.QPushButton(self.tab_2)
        self.assign_load_xlink_btn.setObjectName("assign_load_xlink_btn")
        self.gridLayout.addWidget(self.assign_load_xlink_btn, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.assign_previous_btn = QtWidgets.QPushButton(self.tab_2)
        self.assign_previous_btn.setObjectName("assign_previous_btn")
        self.gridLayout.addWidget(self.assign_previous_btn, 9, 0, 1, 1)
        self.assign_score_accept = QtWidgets.QPushButton(self.tab_2)
        self.assign_score_accept.setStyleSheet("QPushButton:pressed {background-color: rgb(154,205,50)}\n"
"QPushButton {background-color: rgb(107,142,35)}")
        self.assign_score_accept.setObjectName("assign_score_accept")
        self.gridLayout.addWidget(self.assign_score_accept, 6, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 9)
        self.assign_score_good_btn = QtWidgets.QPushButton(self.tab_2)
        self.assign_score_good_btn.setStyleSheet("QPushButton:pressed {background-color: rgb(154,205,50)}\n"
"QPushButton {background-color: rgb(124,252,0)}")
        self.assign_score_good_btn.setObjectName("assign_score_good_btn")
        self.gridLayout.addWidget(self.assign_score_good_btn, 5, 3, 1, 1)
        self.assign_filter_btn = QtWidgets.QPushButton(self.tab_2)
        self.assign_filter_btn.setObjectName("assign_filter_btn")
        self.gridLayout.addWidget(self.assign_filter_btn, 6, 0, 1, 1)
        self.assign_goto_btn = QtWidgets.QPushButton(self.tab_2)
        self.assign_goto_btn.setObjectName("assign_goto_btn")
        self.gridLayout.addWidget(self.assign_goto_btn, 5, 0, 1, 1)
        self.assign_goto_edit = QtWidgets.QLineEdit(self.tab_2)
        self.assign_goto_edit.setObjectName("assign_goto_edit")
        self.gridLayout.addWidget(self.assign_goto_edit, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 5, 1, 1)
        self.assign_filter_dropdown = QtWidgets.QComboBox(self.tab_2)
        self.assign_filter_dropdown.setObjectName("assign_filter_dropdown")
        self.assign_filter_dropdown.addItem("")
        self.assign_filter_dropdown.addItem("")
        self.gridLayout.addWidget(self.assign_filter_dropdown, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 7, 1, 1)
        self.assign_filter_edit = QtWidgets.QLineEdit(self.tab_2)
        self.assign_filter_edit.setObjectName("assign_filter_edit")
        self.gridLayout.addWidget(self.assign_filter_edit, 6, 2, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 6, 8, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.assign_output_btn = QtWidgets.QPushButton(self.tab_2)
        self.assign_output_btn.setObjectName("assign_output_btn")
        self.gridLayout.addWidget(self.assign_output_btn, 1, 8, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 8, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtWidgets.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.assign_filter_dropdown.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "The CroCo Cross-Link Converter"))
        self.label3.setText(_translate("MainWindow", "Input file format:"))
        self.convert_input_dropdown.setStatusTip(_translate("MainWindow", "Format for file input"))
        self.convert_input_dropdown.setItemText(0, _translate("MainWindow", "pLink"))
        self.convert_input_dropdown.setItemText(1, _translate("MainWindow", "Kojak"))
        self.convert_input_dropdown.setItemText(2, _translate("MainWindow", "xTable"))
        self.label4.setText(_translate("MainWindow", "Output File Format"))
        self.convert_output_dropdown.setStatusTip(_translate("MainWindow", "Format to convert file to"))
        self.convert_output_dropdown.setItemText(0, _translate("MainWindow", "xTable"))
        self.convert_load_btn.setText(_translate("MainWindow", "Load file(s)"))
        self.convert_output_btn.setText(_translate("MainWindow", "Output Dir"))
        self.label1.setText(_translate("MainWindow", "Reading From:"))
        self.label2.setText(_translate("MainWindow", "Writing To:"))
        self.convert_quit.setText(_translate("MainWindow", "Quit"))
        self.convert_start.setStatusTip(_translate("MainWindow", "Start the conversion"))
        self.convert_start.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Conversion"))
        self.assign_next_btn.setText(_translate("MainWindow", "Next"))
        self.assign_score_decline_btn.setText(_translate("MainWindow", "Decline [0]"))
        self.assign_score_decline_btn.setShortcut(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Current xlink:"))
        self.assign_score_unsure_btn.setText(_translate("MainWindow", "Unsure [1]"))
        self.assign_score_unsure_btn.setShortcut(_translate("MainWindow", "1"))
        self.assign_start_btn.setText(_translate("MainWindow", "Start assignment"))
        self.assign_load_mgf_btn.setText(_translate("MainWindow", "Load MGF"))
        self.label_4.setText(_translate("MainWindow", "Current Spectrum"))
        self.label_6.setText(_translate("MainWindow", "Precision (ppm)"))
        self.assign_load_xlink_btn.setText(_translate("MainWindow", "Load xlink"))
        self.label.setText(_translate("MainWindow", "Load xlinks:"))
        self.assign_previous_btn.setText(_translate("MainWindow", "Previous"))
        self.assign_score_accept.setText(_translate("MainWindow", "Accept [2]"))
        self.assign_score_accept.setShortcut(_translate("MainWindow", "2"))
        self.assign_score_good_btn.setText(_translate("MainWindow", "Very Good [3]"))
        self.assign_score_good_btn.setShortcut(_translate("MainWindow", "3"))
        self.assign_filter_btn.setText(_translate("MainWindow", "Filter score"))
        self.assign_goto_btn.setText(_translate("MainWindow", "GoTo"))
        self.label_7.setText(_translate("MainWindow", "-"))
        self.assign_filter_dropdown.setCurrentText(_translate("MainWindow", "Less than"))
        self.assign_filter_dropdown.setItemText(0, _translate("MainWindow", "Less than"))
        self.assign_filter_dropdown.setItemText(1, _translate("MainWindow", "Greater than"))
        self.label_8.setText(_translate("MainWindow", "+"))
        self.label_2.setText(_translate("MainWindow", "Load MGF:"))
        self.assign_output_btn.setText(_translate("MainWindow", "Output Dir"))
        self.label_3.setText(_translate("MainWindow", "Output Dir:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Assignment"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Exit the programme"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About CroCo"))
        self.actionAbout.setStatusTip(_translate("MainWindow", "About CroCo"))

import croco_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

